/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvatarLabRouteImport } from './routes/avatar-lab'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TokushoRouteImport } from './routes/tokusho'
import { Route as ActorInterviewTokenRouteImport } from './routes/actor-interview/$token'
import { Route as ApiActorInterviewTurnRouteImport } from './routes/api/actor-interview-turn'
import { Route as ApiAdminDashboardDataRouteImport } from './routes/api/admin-dashboard-data'
import { Route as ApiAdminTriggerActorDiscoveryRouteImport } from './routes/api/admin-trigger-actor-discovery'
import { Route as ApiAgencyDashboardDataRouteImport } from './routes/api/agency-dashboard-data'
import { Route as ApiBulkResearchActorsRouteImport } from './routes/api/bulk-research-actors'
import { Route as ApiCancelSubscriptionRouteImport } from './routes/api/cancel-subscription'
import { Route as ApiCandidateDatabaseRouteImport } from './routes/api/candidate-database'
import { Route as ApiCareerChatRouteImport } from './routes/api/career-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatInterviewInfoRouteImport } from './routes/api/chat-interview-info'
import { Route as ApiChatInterviewTurnRouteImport } from './routes/api/chat-interview-turn'
import { Route as ApiCreateActorInterviewRouteImport } from './routes/api/create-actor-interview'
import { Route as ApiCreatePracticeSessionRouteImport } from './routes/api/create-practice-session'
import { Route as ApiCreateSubscriptionRouteImport } from './routes/api/create-subscription'
import { Route as ApiCustomerPortalRouteImport } from './routes/api/customer-portal'
import { Route as ApiDailyQuestionRouteImport } from './routes/api/daily-question'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiExtractTemplateFieldsRouteImport } from './routes/api/extract-template-fields'
import { Route as ApiGenerateDocumentRouteImport } from './routes/api/generate-document'
import { Route as ApiGenerateSelfAnalysisRouteImport } from './routes/api/generate-self-analysis'
import { Route as ApiInterviewTurnRouteImport } from './routes/api/interview-turn'
import { Route as ApiPredictTicketSalesRouteImport } from './routes/api/predict-ticket-sales'
import { Route as ApiRecordReferralRouteImport } from './routes/api/record-referral'
import { Route as ApiRefineDocumentRouteImport } from './routes/api/refine-document'
import { Route as ApiRegisterDeviceRouteImport } from './routes/api/register-device'
import { Route as ApiReportUsageRouteImport } from './routes/api/report-usage'
import { Route as ApiResearchActorRouteImport } from './routes/api/research-actor'
import { Route as ApiResearchCompanyRouteImport } from './routes/api/research-company'
import { Route as ApiResearchTargetRouteImport } from './routes/api/research-target'
import { Route as ApiSaveActorInterviewRouteImport } from './routes/api/save-actor-interview'
import { Route as ApiSaveInterviewRouteImport } from './routes/api/save-interview'
import { Route as ApiSaveInterviewRecordingRouteImport } from './routes/api/save-interview-recording'
import { Route as ApiScreenActorsBatchRouteImport } from './routes/api/screen-actors-batch'
import { Route as ApiSendInterviewEmailRouteImport } from './routes/api/send-interview-email'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiToggleCandidateBookmarkRouteImport } from './routes/api/toggle-candidate-bookmark'
import { Route as ApiWhisperTranscribeRouteImport } from './routes/api/whisper-transcribe'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as ChatInterviewTokenRouteImport } from './routes/chat-interview/$token'
import { Route as InterviewTokenRouteImport } from './routes/interview/$token'
import { Route as PrivateIndexRouteImport } from './routes/private/index'
import { Route as PrivateAdminRouteImport } from './routes/private/admin'
import { Route as PrivateAgencyRouteImport } from './routes/private/agency'
import { Route as PrivateWelcomeRouteImport } from './routes/private/welcome'
import { Route as ScreeningHistoryRouteImport } from './routes/screening_.history'
import { Route as BusinessActorIndexRouteImport } from './routes/business/actor/index'
import { Route as BusinessActorDatabaseRouteImport } from './routes/business/actor/database'
import { Route as BusinessActorHistoryRouteImport } from './routes/business/actor/history'
import { Route as BusinessActorScreeningRouteImport } from './routes/business/actor/screening'
import { Route as BusinessCompanyIndexRouteImport } from './routes/business/company/index'
import { Route as BusinessCompanyCandidatesRouteImport } from './routes/business/company/candidates'
import { Route as BusinessCompanyHistoryRouteImport } from './routes/business/company/history'
import { Route as BusinessCompanyJobsRouteImport } from './routes/business/company/jobs'
import { Route as BusinessCompanyScreeningRouteImport } from './routes/business/company/screening'
import { Route as BusinessCompanySettingsRouteImport } from './routes/business/company/settings'
import { Route as BusinessSchoolIndexRouteImport } from './routes/business/school/index'
import { Route as BusinessSchoolHistoryRouteImport } from './routes/business/school/history'
import { Route as BusinessSchoolScreeningRouteImport } from './routes/business/school/screening'
import { Route as BusinessSchoolSettingsRouteImport } from './routes/business/school/settings'
import { Route as BusinessSchoolStudentsRouteImport } from './routes/business/school/students'
import { Route as PrivateIndividualIndexRouteImport } from './routes/private/individual/index'
import { Route as PrivateIndividualDailyQuestionsRouteImport } from './routes/private/individual/daily-questions'
import { Route as PrivateIndividualDocumentsRouteImport } from './routes/private/individual/documents'
import { Route as PrivateIndividualHistoryRouteImport } from './routes/private/individual/history'
import { Route as PrivateIndividualOnboardingRouteImport } from './routes/private/individual/onboarding'
import { Route as PrivateIndividualPracticeRouteImport } from './routes/private/individual/practice'
import { Route as PrivateIndividualPrepRouteImport } from './routes/private/individual/prep'
import { Route as PrivateIndividualProfileRouteImport } from './routes/private/individual/profile'
import { Route as PrivateIndividualResearchRouteImport } from './routes/private/individual/research'
import { Route as PrivateIndividualSelfAnalysisRouteImport } from './routes/private/individual/self-analysis'
import { Route as PrivateStudentIndexRouteImport } from './routes/private/student/index'
import { Route as PrivateStudentDailyQuestionsRouteImport } from './routes/private/student/daily-questions'
import { Route as PrivateStudentDocumentsRouteImport } from './routes/private/student/documents'
import { Route as PrivateStudentHistoryRouteImport } from './routes/private/student/history'
import { Route as PrivateStudentOnboardingRouteImport } from './routes/private/student/onboarding'
import { Route as PrivateStudentPracticeRouteImport } from './routes/private/student/practice'
import { Route as PrivateStudentProfileRouteImport } from './routes/private/student/profile'
import { Route as PrivateStudentResearchRouteImport } from './routes/private/student/research'
import { Route as PrivateStudentSelfAnalysisRouteImport } from './routes/private/student/self-analysis'
import { Route as PrivateStudentStatementRouteImport } from './routes/private/student/statement'
import { Route as BusinessActorScreeningHistoryRouteImport } from './routes/business/actor/screening_/history'
import { Route as BusinessCompanyScreeningHistoryRouteImport } from './routes/business/company/screening_.history'
import { Route as BusinessSchoolScreeningHistoryRouteImport } from './routes/business/school/screening_.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarLabRoute = AvatarLabRouteImport.update({
  id: '/avatar-lab',
  path: '/avatar-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TokushoRoute = TokushoRouteImport.update({
  id: '/tokusho',
  path: '/tokusho',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorInterviewTokenRoute = ActorInterviewTokenRouteImport.update({
  id: '/actor-interview/$token',
  path: '/actor-interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActorInterviewTurnRoute = ApiActorInterviewTurnRouteImport.update({
  id: '/api/actor-interview-turn',
  path: '/api/actor-interview-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardDataRoute = ApiAdminDashboardDataRouteImport.update({
  id: '/api/admin-dashboard-data',
  path: '/api/admin-dashboard-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTriggerActorDiscoveryRoute =
  ApiAdminTriggerActorDiscoveryRouteImport.update({
    id: '/api/admin-trigger-actor-discovery',
    path: '/api/admin-trigger-actor-discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgencyDashboardDataRoute = ApiAgencyDashboardDataRouteImport.update({
  id: '/api/agency-dashboard-data',
  path: '/api/agency-dashboard-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBulkResearchActorsRoute = ApiBulkResearchActorsRouteImport.update({
  id: '/api/bulk-research-actors',
  path: '/api/bulk-research-actors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCancelSubscriptionRoute = ApiCancelSubscriptionRouteImport.update({
  id: '/api/cancel-subscription',
  path: '/api/cancel-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidateDatabaseRoute = ApiCandidateDatabaseRouteImport.update({
  id: '/api/candidate-database',
  path: '/api/candidate-database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerChatRoute = ApiCareerChatRouteImport.update({
  id: '/api/career-chat',
  path: '/api/career-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatInterviewInfoRoute = ApiChatInterviewInfoRouteImport.update({
  id: '/api/chat-interview-info',
  path: '/api/chat-interview-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatInterviewTurnRoute = ApiChatInterviewTurnRouteImport.update({
  id: '/api/chat-interview-turn',
  path: '/api/chat-interview-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateActorInterviewRoute = ApiCreateActorInterviewRouteImport.update({
  id: '/api/create-actor-interview',
  path: '/api/create-actor-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePracticeSessionRoute =
  ApiCreatePracticeSessionRouteImport.update({
    id: '/api/create-practice-session',
    path: '/api/create-practice-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreateSubscriptionRoute = ApiCreateSubscriptionRouteImport.update({
  id: '/api/create-subscription',
  path: '/api/create-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerPortalRoute = ApiCustomerPortalRouteImport.update({
  id: '/api/customer-portal',
  path: '/api/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyQuestionRoute = ApiDailyQuestionRouteImport.update({
  id: '/api/daily-question',
  path: '/api/daily-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractTemplateFieldsRoute =
  ApiExtractTemplateFieldsRouteImport.update({
    id: '/api/extract-template-fields',
    path: '/api/extract-template-fields',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGenerateDocumentRoute = ApiGenerateDocumentRouteImport.update({
  id: '/api/generate-document',
  path: '/api/generate-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSelfAnalysisRoute = ApiGenerateSelfAnalysisRouteImport.update({
  id: '/api/generate-self-analysis',
  path: '/api/generate-self-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewTurnRoute = ApiInterviewTurnRouteImport.update({
  id: '/api/interview-turn',
  path: '/api/interview-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictTicketSalesRoute = ApiPredictTicketSalesRouteImport.update({
  id: '/api/predict-ticket-sales',
  path: '/api/predict-ticket-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordReferralRoute = ApiRecordReferralRouteImport.update({
  id: '/api/record-referral',
  path: '/api/record-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefineDocumentRoute = ApiRefineDocumentRouteImport.update({
  id: '/api/refine-document',
  path: '/api/refine-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterDeviceRoute = ApiRegisterDeviceRouteImport.update({
  id: '/api/register-device',
  path: '/api/register-device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportUsageRoute = ApiReportUsageRouteImport.update({
  id: '/api/report-usage',
  path: '/api/report-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchActorRoute = ApiResearchActorRouteImport.update({
  id: '/api/research-actor',
  path: '/api/research-actor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchCompanyRoute = ApiResearchCompanyRouteImport.update({
  id: '/api/research-company',
  path: '/api/research-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchTargetRoute = ApiResearchTargetRouteImport.update({
  id: '/api/research-target',
  path: '/api/research-target',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveActorInterviewRoute = ApiSaveActorInterviewRouteImport.update({
  id: '/api/save-actor-interview',
  path: '/api/save-actor-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveInterviewRoute = ApiSaveInterviewRouteImport.update({
  id: '/api/save-interview',
  path: '/api/save-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveInterviewRecordingRoute =
  ApiSaveInterviewRecordingRouteImport.update({
    id: '/api/save-interview-recording',
    path: '/api/save-interview-recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScreenActorsBatchRoute = ApiScreenActorsBatchRouteImport.update({
  id: '/api/screen-actors-batch',
  path: '/api/screen-actors-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendInterviewEmailRoute = ApiSendInterviewEmailRouteImport.update({
  id: '/api/send-interview-email',
  path: '/api/send-interview-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToggleCandidateBookmarkRoute =
  ApiToggleCandidateBookmarkRouteImport.update({
    id: '/api/toggle-candidate-bookmark',
    path: '/api/toggle-candidate-bookmark',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhisperTranscribeRoute = ApiWhisperTranscribeRouteImport.update({
  id: '/api/whisper-transcribe',
  path: '/api/whisper-transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInterviewTokenRoute = ChatInterviewTokenRouteImport.update({
  id: '/chat-interview/$token',
  path: '/chat-interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTokenRoute = InterviewTokenRouteImport.update({
  id: '/interview/$token',
  path: '/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/private/',
  path: '/private/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminRoute = PrivateAdminRouteImport.update({
  id: '/private/admin',
  path: '/private/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAgencyRoute = PrivateAgencyRouteImport.update({
  id: '/private/agency',
  path: '/private/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateWelcomeRoute = PrivateWelcomeRouteImport.update({
  id: '/private/welcome',
  path: '/private/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningHistoryRoute = ScreeningHistoryRouteImport.update({
  id: '/screening_/history',
  path: '/screening/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessActorIndexRoute = BusinessActorIndexRouteImport.update({
  id: '/business/actor/',
  path: '/business/actor/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessActorDatabaseRoute = BusinessActorDatabaseRouteImport.update({
  id: '/business/actor/database',
  path: '/business/actor/database',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessActorHistoryRoute = BusinessActorHistoryRouteImport.update({
  id: '/business/actor/history',
  path: '/business/actor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessActorScreeningRoute = BusinessActorScreeningRouteImport.update({
  id: '/business/actor/screening',
  path: '/business/actor/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCompanyIndexRoute = BusinessCompanyIndexRouteImport.update({
  id: '/business/company/',
  path: '/business/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCompanyCandidatesRoute =
  BusinessCompanyCandidatesRouteImport.update({
    id: '/business/company/candidates',
    path: '/business/company/candidates',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessCompanyHistoryRoute = BusinessCompanyHistoryRouteImport.update({
  id: '/business/company/history',
  path: '/business/company/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCompanyJobsRoute = BusinessCompanyJobsRouteImport.update({
  id: '/business/company/jobs',
  path: '/business/company/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCompanyScreeningRoute =
  BusinessCompanyScreeningRouteImport.update({
    id: '/business/company/screening',
    path: '/business/company/screening',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessCompanySettingsRoute = BusinessCompanySettingsRouteImport.update({
  id: '/business/company/settings',
  path: '/business/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSchoolIndexRoute = BusinessSchoolIndexRouteImport.update({
  id: '/business/school/',
  path: '/business/school/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSchoolHistoryRoute = BusinessSchoolHistoryRouteImport.update({
  id: '/business/school/history',
  path: '/business/school/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSchoolScreeningRoute = BusinessSchoolScreeningRouteImport.update({
  id: '/business/school/screening',
  path: '/business/school/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSchoolSettingsRoute = BusinessSchoolSettingsRouteImport.update({
  id: '/business/school/settings',
  path: '/business/school/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSchoolStudentsRoute = BusinessSchoolStudentsRouteImport.update({
  id: '/business/school/students',
  path: '/business/school/students',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndividualIndexRoute = PrivateIndividualIndexRouteImport.update({
  id: '/private/individual/',
  path: '/private/individual/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndividualDailyQuestionsRoute =
  PrivateIndividualDailyQuestionsRouteImport.update({
    id: '/private/individual/daily-questions',
    path: '/private/individual/daily-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualDocumentsRoute =
  PrivateIndividualDocumentsRouteImport.update({
    id: '/private/individual/documents',
    path: '/private/individual/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualHistoryRoute =
  PrivateIndividualHistoryRouteImport.update({
    id: '/private/individual/history',
    path: '/private/individual/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualOnboardingRoute =
  PrivateIndividualOnboardingRouteImport.update({
    id: '/private/individual/onboarding',
    path: '/private/individual/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualPracticeRoute =
  PrivateIndividualPracticeRouteImport.update({
    id: '/private/individual/practice',
    path: '/private/individual/practice',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualPrepRoute = PrivateIndividualPrepRouteImport.update({
  id: '/private/individual/prep',
  path: '/private/individual/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndividualProfileRoute =
  PrivateIndividualProfileRouteImport.update({
    id: '/private/individual/profile',
    path: '/private/individual/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualResearchRoute =
  PrivateIndividualResearchRouteImport.update({
    id: '/private/individual/research',
    path: '/private/individual/research',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateIndividualSelfAnalysisRoute =
  PrivateIndividualSelfAnalysisRouteImport.update({
    id: '/private/individual/self-analysis',
    path: '/private/individual/self-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateStudentIndexRoute = PrivateStudentIndexRouteImport.update({
  id: '/private/student/',
  path: '/private/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentDailyQuestionsRoute =
  PrivateStudentDailyQuestionsRouteImport.update({
    id: '/private/student/daily-questions',
    path: '/private/student/daily-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateStudentDocumentsRoute = PrivateStudentDocumentsRouteImport.update({
  id: '/private/student/documents',
  path: '/private/student/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentHistoryRoute = PrivateStudentHistoryRouteImport.update({
  id: '/private/student/history',
  path: '/private/student/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentOnboardingRoute =
  PrivateStudentOnboardingRouteImport.update({
    id: '/private/student/onboarding',
    path: '/private/student/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateStudentPracticeRoute = PrivateStudentPracticeRouteImport.update({
  id: '/private/student/practice',
  path: '/private/student/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentProfileRoute = PrivateStudentProfileRouteImport.update({
  id: '/private/student/profile',
  path: '/private/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentResearchRoute = PrivateStudentResearchRouteImport.update({
  id: '/private/student/research',
  path: '/private/student/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStudentSelfAnalysisRoute =
  PrivateStudentSelfAnalysisRouteImport.update({
    id: '/private/student/self-analysis',
    path: '/private/student/self-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateStudentStatementRoute = PrivateStudentStatementRouteImport.update({
  id: '/private/student/statement',
  path: '/private/student/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessActorScreeningHistoryRoute =
  BusinessActorScreeningHistoryRouteImport.update({
    id: '/business/actor/screening_/history',
    path: '/business/actor/screening/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessCompanyScreeningHistoryRoute =
  BusinessCompanyScreeningHistoryRouteImport.update({
    id: '/business/company/screening_/history',
    path: '/business/company/screening/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessSchoolScreeningHistoryRoute =
  BusinessSchoolScreeningHistoryRouteImport.update({
    id: '/business/school/screening_/history',
    path: '/business/school/screening/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar-lab': typeof AvatarLabRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/screening': typeof ScreeningRoute
  '/terms': typeof TermsRoute
  '/tokusho': typeof TokushoRoute
  '/actor-interview/$token': typeof ActorInterviewTokenRoute
  '/api/actor-interview-turn': typeof ApiActorInterviewTurnRoute
  '/api/admin-dashboard-data': typeof ApiAdminDashboardDataRoute
  '/api/admin-trigger-actor-discovery': typeof ApiAdminTriggerActorDiscoveryRoute
  '/api/agency-dashboard-data': typeof ApiAgencyDashboardDataRoute
  '/api/bulk-research-actors': typeof ApiBulkResearchActorsRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/candidate-database': typeof ApiCandidateDatabaseRoute
  '/api/career-chat': typeof ApiCareerChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-interview-info': typeof ApiChatInterviewInfoRoute
  '/api/chat-interview-turn': typeof ApiChatInterviewTurnRoute
  '/api/create-actor-interview': typeof ApiCreateActorInterviewRoute
  '/api/create-practice-session': typeof ApiCreatePracticeSessionRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/customer-portal': typeof ApiCustomerPortalRoute
  '/api/daily-question': typeof ApiDailyQuestionRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/extract-template-fields': typeof ApiExtractTemplateFieldsRoute
  '/api/generate-document': typeof ApiGenerateDocumentRoute
  '/api/generate-self-analysis': typeof ApiGenerateSelfAnalysisRoute
  '/api/interview-turn': typeof ApiInterviewTurnRoute
  '/api/predict-ticket-sales': typeof ApiPredictTicketSalesRoute
  '/api/record-referral': typeof ApiRecordReferralRoute
  '/api/refine-document': typeof ApiRefineDocumentRoute
  '/api/register-device': typeof ApiRegisterDeviceRoute
  '/api/report-usage': typeof ApiReportUsageRoute
  '/api/research-actor': typeof ApiResearchActorRoute
  '/api/research-company': typeof ApiResearchCompanyRoute
  '/api/research-target': typeof ApiResearchTargetRoute
  '/api/save-actor-interview': typeof ApiSaveActorInterviewRoute
  '/api/save-interview': typeof ApiSaveInterviewRoute
  '/api/save-interview-recording': typeof ApiSaveInterviewRecordingRoute
  '/api/screen-actors-batch': typeof ApiScreenActorsBatchRoute
  '/api/send-interview-email': typeof ApiSendInterviewEmailRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/toggle-candidate-bookmark': typeof ApiToggleCandidateBookmarkRoute
  '/api/whisper-transcribe': typeof ApiWhisperTranscribeRoute
  '/chat-interview/$token': typeof ChatInterviewTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/private/admin': typeof PrivateAdminRoute
  '/private/agency': typeof PrivateAgencyRoute
  '/private/welcome': typeof PrivateWelcomeRoute
  '/screening/history': typeof ScreeningHistoryRoute
  '/business/': typeof BusinessIndexRoute
  '/private/': typeof PrivateIndexRoute
  '/business/actor/database': typeof BusinessActorDatabaseRoute
  '/business/actor/history': typeof BusinessActorHistoryRoute
  '/business/actor/screening': typeof BusinessActorScreeningRoute
  '/business/company/candidates': typeof BusinessCompanyCandidatesRoute
  '/business/company/history': typeof BusinessCompanyHistoryRoute
  '/business/company/jobs': typeof BusinessCompanyJobsRoute
  '/business/company/screening': typeof BusinessCompanyScreeningRoute
  '/business/company/settings': typeof BusinessCompanySettingsRoute
  '/business/school/history': typeof BusinessSchoolHistoryRoute
  '/business/school/screening': typeof BusinessSchoolScreeningRoute
  '/business/school/settings': typeof BusinessSchoolSettingsRoute
  '/business/school/students': typeof BusinessSchoolStudentsRoute
  '/private/individual/daily-questions': typeof PrivateIndividualDailyQuestionsRoute
  '/private/individual/documents': typeof PrivateIndividualDocumentsRoute
  '/private/individual/history': typeof PrivateIndividualHistoryRoute
  '/private/individual/onboarding': typeof PrivateIndividualOnboardingRoute
  '/private/individual/practice': typeof PrivateIndividualPracticeRoute
  '/private/individual/prep': typeof PrivateIndividualPrepRoute
  '/private/individual/profile': typeof PrivateIndividualProfileRoute
  '/private/individual/research': typeof PrivateIndividualResearchRoute
  '/private/individual/self-analysis': typeof PrivateIndividualSelfAnalysisRoute
  '/private/student/daily-questions': typeof PrivateStudentDailyQuestionsRoute
  '/private/student/documents': typeof PrivateStudentDocumentsRoute
  '/private/student/history': typeof PrivateStudentHistoryRoute
  '/private/student/onboarding': typeof PrivateStudentOnboardingRoute
  '/private/student/practice': typeof PrivateStudentPracticeRoute
  '/private/student/profile': typeof PrivateStudentProfileRoute
  '/private/student/research': typeof PrivateStudentResearchRoute
  '/private/student/self-analysis': typeof PrivateStudentSelfAnalysisRoute
  '/private/student/statement': typeof PrivateStudentStatementRoute
  '/business/actor/': typeof BusinessActorIndexRoute
  '/business/company/': typeof BusinessCompanyIndexRoute
  '/business/school/': typeof BusinessSchoolIndexRoute
  '/private/individual/': typeof PrivateIndividualIndexRoute
  '/private/student/': typeof PrivateStudentIndexRoute
  '/business/actor/screening/history': typeof BusinessActorScreeningHistoryRoute
  '/business/company/screening/history': typeof BusinessCompanyScreeningHistoryRoute
  '/business/school/screening/history': typeof BusinessSchoolScreeningHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar-lab': typeof AvatarLabRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/screening': typeof ScreeningRoute
  '/terms': typeof TermsRoute
  '/tokusho': typeof TokushoRoute
  '/actor-interview/$token': typeof ActorInterviewTokenRoute
  '/api/actor-interview-turn': typeof ApiActorInterviewTurnRoute
  '/api/admin-dashboard-data': typeof ApiAdminDashboardDataRoute
  '/api/admin-trigger-actor-discovery': typeof ApiAdminTriggerActorDiscoveryRoute
  '/api/agency-dashboard-data': typeof ApiAgencyDashboardDataRoute
  '/api/bulk-research-actors': typeof ApiBulkResearchActorsRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/candidate-database': typeof ApiCandidateDatabaseRoute
  '/api/career-chat': typeof ApiCareerChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-interview-info': typeof ApiChatInterviewInfoRoute
  '/api/chat-interview-turn': typeof ApiChatInterviewTurnRoute
  '/api/create-actor-interview': typeof ApiCreateActorInterviewRoute
  '/api/create-practice-session': typeof ApiCreatePracticeSessionRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/customer-portal': typeof ApiCustomerPortalRoute
  '/api/daily-question': typeof ApiDailyQuestionRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/extract-template-fields': typeof ApiExtractTemplateFieldsRoute
  '/api/generate-document': typeof ApiGenerateDocumentRoute
  '/api/generate-self-analysis': typeof ApiGenerateSelfAnalysisRoute
  '/api/interview-turn': typeof ApiInterviewTurnRoute
  '/api/predict-ticket-sales': typeof ApiPredictTicketSalesRoute
  '/api/record-referral': typeof ApiRecordReferralRoute
  '/api/refine-document': typeof ApiRefineDocumentRoute
  '/api/register-device': typeof ApiRegisterDeviceRoute
  '/api/report-usage': typeof ApiReportUsageRoute
  '/api/research-actor': typeof ApiResearchActorRoute
  '/api/research-company': typeof ApiResearchCompanyRoute
  '/api/research-target': typeof ApiResearchTargetRoute
  '/api/save-actor-interview': typeof ApiSaveActorInterviewRoute
  '/api/save-interview': typeof ApiSaveInterviewRoute
  '/api/save-interview-recording': typeof ApiSaveInterviewRecordingRoute
  '/api/screen-actors-batch': typeof ApiScreenActorsBatchRoute
  '/api/send-interview-email': typeof ApiSendInterviewEmailRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/toggle-candidate-bookmark': typeof ApiToggleCandidateBookmarkRoute
  '/api/whisper-transcribe': typeof ApiWhisperTranscribeRoute
  '/chat-interview/$token': typeof ChatInterviewTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/private/admin': typeof PrivateAdminRoute
  '/private/agency': typeof PrivateAgencyRoute
  '/private/welcome': typeof PrivateWelcomeRoute
  '/screening/history': typeof ScreeningHistoryRoute
  '/business': typeof BusinessIndexRoute
  '/private': typeof PrivateIndexRoute
  '/business/actor/database': typeof BusinessActorDatabaseRoute
  '/business/actor/history': typeof BusinessActorHistoryRoute
  '/business/actor/screening': typeof BusinessActorScreeningRoute
  '/business/company/candidates': typeof BusinessCompanyCandidatesRoute
  '/business/company/history': typeof BusinessCompanyHistoryRoute
  '/business/company/jobs': typeof BusinessCompanyJobsRoute
  '/business/company/screening': typeof BusinessCompanyScreeningRoute
  '/business/company/settings': typeof BusinessCompanySettingsRoute
  '/business/school/history': typeof BusinessSchoolHistoryRoute
  '/business/school/screening': typeof BusinessSchoolScreeningRoute
  '/business/school/settings': typeof BusinessSchoolSettingsRoute
  '/business/school/students': typeof BusinessSchoolStudentsRoute
  '/private/individual/daily-questions': typeof PrivateIndividualDailyQuestionsRoute
  '/private/individual/documents': typeof PrivateIndividualDocumentsRoute
  '/private/individual/history': typeof PrivateIndividualHistoryRoute
  '/private/individual/onboarding': typeof PrivateIndividualOnboardingRoute
  '/private/individual/practice': typeof PrivateIndividualPracticeRoute
  '/private/individual/prep': typeof PrivateIndividualPrepRoute
  '/private/individual/profile': typeof PrivateIndividualProfileRoute
  '/private/individual/research': typeof PrivateIndividualResearchRoute
  '/private/individual/self-analysis': typeof PrivateIndividualSelfAnalysisRoute
  '/private/student/daily-questions': typeof PrivateStudentDailyQuestionsRoute
  '/private/student/documents': typeof PrivateStudentDocumentsRoute
  '/private/student/history': typeof PrivateStudentHistoryRoute
  '/private/student/onboarding': typeof PrivateStudentOnboardingRoute
  '/private/student/practice': typeof PrivateStudentPracticeRoute
  '/private/student/profile': typeof PrivateStudentProfileRoute
  '/private/student/research': typeof PrivateStudentResearchRoute
  '/private/student/self-analysis': typeof PrivateStudentSelfAnalysisRoute
  '/private/student/statement': typeof PrivateStudentStatementRoute
  '/business/actor': typeof BusinessActorIndexRoute
  '/business/company': typeof BusinessCompanyIndexRoute
  '/business/school': typeof BusinessSchoolIndexRoute
  '/private/individual': typeof PrivateIndividualIndexRoute
  '/private/student': typeof PrivateStudentIndexRoute
  '/business/actor/screening/history': typeof BusinessActorScreeningHistoryRoute
  '/business/company/screening/history': typeof BusinessCompanyScreeningHistoryRoute
  '/business/school/screening/history': typeof BusinessSchoolScreeningHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar-lab': typeof AvatarLabRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/screening': typeof ScreeningRoute
  '/terms': typeof TermsRoute
  '/tokusho': typeof TokushoRoute
  '/actor-interview/$token': typeof ActorInterviewTokenRoute
  '/api/actor-interview-turn': typeof ApiActorInterviewTurnRoute
  '/api/admin-dashboard-data': typeof ApiAdminDashboardDataRoute
  '/api/admin-trigger-actor-discovery': typeof ApiAdminTriggerActorDiscoveryRoute
  '/api/agency-dashboard-data': typeof ApiAgencyDashboardDataRoute
  '/api/bulk-research-actors': typeof ApiBulkResearchActorsRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/candidate-database': typeof ApiCandidateDatabaseRoute
  '/api/career-chat': typeof ApiCareerChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-interview-info': typeof ApiChatInterviewInfoRoute
  '/api/chat-interview-turn': typeof ApiChatInterviewTurnRoute
  '/api/create-actor-interview': typeof ApiCreateActorInterviewRoute
  '/api/create-practice-session': typeof ApiCreatePracticeSessionRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/customer-portal': typeof ApiCustomerPortalRoute
  '/api/daily-question': typeof ApiDailyQuestionRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/extract-template-fields': typeof ApiExtractTemplateFieldsRoute
  '/api/generate-document': typeof ApiGenerateDocumentRoute
  '/api/generate-self-analysis': typeof ApiGenerateSelfAnalysisRoute
  '/api/interview-turn': typeof ApiInterviewTurnRoute
  '/api/predict-ticket-sales': typeof ApiPredictTicketSalesRoute
  '/api/record-referral': typeof ApiRecordReferralRoute
  '/api/refine-document': typeof ApiRefineDocumentRoute
  '/api/register-device': typeof ApiRegisterDeviceRoute
  '/api/report-usage': typeof ApiReportUsageRoute
  '/api/research-actor': typeof ApiResearchActorRoute
  '/api/research-company': typeof ApiResearchCompanyRoute
  '/api/research-target': typeof ApiResearchTargetRoute
  '/api/save-actor-interview': typeof ApiSaveActorInterviewRoute
  '/api/save-interview': typeof ApiSaveInterviewRoute
  '/api/save-interview-recording': typeof ApiSaveInterviewRecordingRoute
  '/api/screen-actors-batch': typeof ApiScreenActorsBatchRoute
  '/api/send-interview-email': typeof ApiSendInterviewEmailRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/toggle-candidate-bookmark': typeof ApiToggleCandidateBookmarkRoute
  '/api/whisper-transcribe': typeof ApiWhisperTranscribeRoute
  '/chat-interview/$token': typeof ChatInterviewTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/private/admin': typeof PrivateAdminRoute
  '/private/agency': typeof PrivateAgencyRoute
  '/private/welcome': typeof PrivateWelcomeRoute
  '/screening_/history': typeof ScreeningHistoryRoute
  '/business/': typeof BusinessIndexRoute
  '/private/': typeof PrivateIndexRoute
  '/business/actor/database': typeof BusinessActorDatabaseRoute
  '/business/actor/history': typeof BusinessActorHistoryRoute
  '/business/actor/screening': typeof BusinessActorScreeningRoute
  '/business/company/candidates': typeof BusinessCompanyCandidatesRoute
  '/business/company/history': typeof BusinessCompanyHistoryRoute
  '/business/company/jobs': typeof BusinessCompanyJobsRoute
  '/business/company/screening': typeof BusinessCompanyScreeningRoute
  '/business/company/settings': typeof BusinessCompanySettingsRoute
  '/business/school/history': typeof BusinessSchoolHistoryRoute
  '/business/school/screening': typeof BusinessSchoolScreeningRoute
  '/business/school/settings': typeof BusinessSchoolSettingsRoute
  '/business/school/students': typeof BusinessSchoolStudentsRoute
  '/private/individual/daily-questions': typeof PrivateIndividualDailyQuestionsRoute
  '/private/individual/documents': typeof PrivateIndividualDocumentsRoute
  '/private/individual/history': typeof PrivateIndividualHistoryRoute
  '/private/individual/onboarding': typeof PrivateIndividualOnboardingRoute
  '/private/individual/practice': typeof PrivateIndividualPracticeRoute
  '/private/individual/prep': typeof PrivateIndividualPrepRoute
  '/private/individual/profile': typeof PrivateIndividualProfileRoute
  '/private/individual/research': typeof PrivateIndividualResearchRoute
  '/private/individual/self-analysis': typeof PrivateIndividualSelfAnalysisRoute
  '/private/student/daily-questions': typeof PrivateStudentDailyQuestionsRoute
  '/private/student/documents': typeof PrivateStudentDocumentsRoute
  '/private/student/history': typeof PrivateStudentHistoryRoute
  '/private/student/onboarding': typeof PrivateStudentOnboardingRoute
  '/private/student/practice': typeof PrivateStudentPracticeRoute
  '/private/student/profile': typeof PrivateStudentProfileRoute
  '/private/student/research': typeof PrivateStudentResearchRoute
  '/private/student/self-analysis': typeof PrivateStudentSelfAnalysisRoute
  '/private/student/statement': typeof PrivateStudentStatementRoute
  '/business/actor/': typeof BusinessActorIndexRoute
  '/business/company/': typeof BusinessCompanyIndexRoute
  '/business/school/': typeof BusinessSchoolIndexRoute
  '/private/individual/': typeof PrivateIndividualIndexRoute
  '/private/student/': typeof PrivateStudentIndexRoute
  '/business/actor/screening_/history': typeof BusinessActorScreeningHistoryRoute
  '/business/company/screening_/history': typeof BusinessCompanyScreeningHistoryRoute
  '/business/school/screening_/history': typeof BusinessSchoolScreeningHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar-lab'
    | '/history'
    | '/home'
    | '/login'
    | '/mypage'
    | '/pricing'
    | '/privacy'
    | '/screening'
    | '/terms'
    | '/tokusho'
    | '/actor-interview/$token'
    | '/api/actor-interview-turn'
    | '/api/admin-dashboard-data'
    | '/api/admin-trigger-actor-discovery'
    | '/api/agency-dashboard-data'
    | '/api/bulk-research-actors'
    | '/api/cancel-subscription'
    | '/api/candidate-database'
    | '/api/career-chat'
    | '/api/chat'
    | '/api/chat-interview-info'
    | '/api/chat-interview-turn'
    | '/api/create-actor-interview'
    | '/api/create-practice-session'
    | '/api/create-subscription'
    | '/api/customer-portal'
    | '/api/daily-question'
    | '/api/delete-account'
    | '/api/extract-template-fields'
    | '/api/generate-document'
    | '/api/generate-self-analysis'
    | '/api/interview-turn'
    | '/api/predict-ticket-sales'
    | '/api/record-referral'
    | '/api/refine-document'
    | '/api/register-device'
    | '/api/report-usage'
    | '/api/research-actor'
    | '/api/research-company'
    | '/api/research-target'
    | '/api/save-actor-interview'
    | '/api/save-interview'
    | '/api/save-interview-recording'
    | '/api/screen-actors-batch'
    | '/api/send-interview-email'
    | '/api/stripe-webhook'
    | '/api/toggle-candidate-bookmark'
    | '/api/whisper-transcribe'
    | '/chat-interview/$token'
    | '/interview/$token'
    | '/private/admin'
    | '/private/agency'
    | '/private/welcome'
    | '/screening/history'
    | '/business/'
    | '/private/'
    | '/business/actor/database'
    | '/business/actor/history'
    | '/business/actor/screening'
    | '/business/company/candidates'
    | '/business/company/history'
    | '/business/company/jobs'
    | '/business/company/screening'
    | '/business/company/settings'
    | '/business/school/history'
    | '/business/school/screening'
    | '/business/school/settings'
    | '/business/school/students'
    | '/private/individual/daily-questions'
    | '/private/individual/documents'
    | '/private/individual/history'
    | '/private/individual/onboarding'
    | '/private/individual/practice'
    | '/private/individual/prep'
    | '/private/individual/profile'
    | '/private/individual/research'
    | '/private/individual/self-analysis'
    | '/private/student/daily-questions'
    | '/private/student/documents'
    | '/private/student/history'
    | '/private/student/onboarding'
    | '/private/student/practice'
    | '/private/student/profile'
    | '/private/student/research'
    | '/private/student/self-analysis'
    | '/private/student/statement'
    | '/business/actor/'
    | '/business/company/'
    | '/business/school/'
    | '/private/individual/'
    | '/private/student/'
    | '/business/actor/screening/history'
    | '/business/company/screening/history'
    | '/business/school/screening/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar-lab'
    | '/history'
    | '/home'
    | '/login'
    | '/mypage'
    | '/pricing'
    | '/privacy'
    | '/screening'
    | '/terms'
    | '/tokusho'
    | '/actor-interview/$token'
    | '/api/actor-interview-turn'
    | '/api/admin-dashboard-data'
    | '/api/admin-trigger-actor-discovery'
    | '/api/agency-dashboard-data'
    | '/api/bulk-research-actors'
    | '/api/cancel-subscription'
    | '/api/candidate-database'
    | '/api/career-chat'
    | '/api/chat'
    | '/api/chat-interview-info'
    | '/api/chat-interview-turn'
    | '/api/create-actor-interview'
    | '/api/create-practice-session'
    | '/api/create-subscription'
    | '/api/customer-portal'
    | '/api/daily-question'
    | '/api/delete-account'
    | '/api/extract-template-fields'
    | '/api/generate-document'
    | '/api/generate-self-analysis'
    | '/api/interview-turn'
    | '/api/predict-ticket-sales'
    | '/api/record-referral'
    | '/api/refine-document'
    | '/api/register-device'
    | '/api/report-usage'
    | '/api/research-actor'
    | '/api/research-company'
    | '/api/research-target'
    | '/api/save-actor-interview'
    | '/api/save-interview'
    | '/api/save-interview-recording'
    | '/api/screen-actors-batch'
    | '/api/send-interview-email'
    | '/api/stripe-webhook'
    | '/api/toggle-candidate-bookmark'
    | '/api/whisper-transcribe'
    | '/chat-interview/$token'
    | '/interview/$token'
    | '/private/admin'
    | '/private/agency'
    | '/private/welcome'
    | '/screening/history'
    | '/business'
    | '/private'
    | '/business/actor/database'
    | '/business/actor/history'
    | '/business/actor/screening'
    | '/business/company/candidates'
    | '/business/company/history'
    | '/business/company/jobs'
    | '/business/company/screening'
    | '/business/company/settings'
    | '/business/school/history'
    | '/business/school/screening'
    | '/business/school/settings'
    | '/business/school/students'
    | '/private/individual/daily-questions'
    | '/private/individual/documents'
    | '/private/individual/history'
    | '/private/individual/onboarding'
    | '/private/individual/practice'
    | '/private/individual/prep'
    | '/private/individual/profile'
    | '/private/individual/research'
    | '/private/individual/self-analysis'
    | '/private/student/daily-questions'
    | '/private/student/documents'
    | '/private/student/history'
    | '/private/student/onboarding'
    | '/private/student/practice'
    | '/private/student/profile'
    | '/private/student/research'
    | '/private/student/self-analysis'
    | '/private/student/statement'
    | '/business/actor'
    | '/business/company'
    | '/business/school'
    | '/private/individual'
    | '/private/student'
    | '/business/actor/screening/history'
    | '/business/company/screening/history'
    | '/business/school/screening/history'
  id:
    | '__root__'
    | '/'
    | '/avatar-lab'
    | '/history'
    | '/home'
    | '/login'
    | '/mypage'
    | '/pricing'
    | '/privacy'
    | '/screening'
    | '/terms'
    | '/tokusho'
    | '/actor-interview/$token'
    | '/api/actor-interview-turn'
    | '/api/admin-dashboard-data'
    | '/api/admin-trigger-actor-discovery'
    | '/api/agency-dashboard-data'
    | '/api/bulk-research-actors'
    | '/api/cancel-subscription'
    | '/api/candidate-database'
    | '/api/career-chat'
    | '/api/chat'
    | '/api/chat-interview-info'
    | '/api/chat-interview-turn'
    | '/api/create-actor-interview'
    | '/api/create-practice-session'
    | '/api/create-subscription'
    | '/api/customer-portal'
    | '/api/daily-question'
    | '/api/delete-account'
    | '/api/extract-template-fields'
    | '/api/generate-document'
    | '/api/generate-self-analysis'
    | '/api/interview-turn'
    | '/api/predict-ticket-sales'
    | '/api/record-referral'
    | '/api/refine-document'
    | '/api/register-device'
    | '/api/report-usage'
    | '/api/research-actor'
    | '/api/research-company'
    | '/api/research-target'
    | '/api/save-actor-interview'
    | '/api/save-interview'
    | '/api/save-interview-recording'
    | '/api/screen-actors-batch'
    | '/api/send-interview-email'
    | '/api/stripe-webhook'
    | '/api/toggle-candidate-bookmark'
    | '/api/whisper-transcribe'
    | '/chat-interview/$token'
    | '/interview/$token'
    | '/private/admin'
    | '/private/agency'
    | '/private/welcome'
    | '/screening_/history'
    | '/business/'
    | '/private/'
    | '/business/actor/database'
    | '/business/actor/history'
    | '/business/actor/screening'
    | '/business/company/candidates'
    | '/business/company/history'
    | '/business/company/jobs'
    | '/business/company/screening'
    | '/business/company/settings'
    | '/business/school/history'
    | '/business/school/screening'
    | '/business/school/settings'
    | '/business/school/students'
    | '/private/individual/daily-questions'
    | '/private/individual/documents'
    | '/private/individual/history'
    | '/private/individual/onboarding'
    | '/private/individual/practice'
    | '/private/individual/prep'
    | '/private/individual/profile'
    | '/private/individual/research'
    | '/private/individual/self-analysis'
    | '/private/student/daily-questions'
    | '/private/student/documents'
    | '/private/student/history'
    | '/private/student/onboarding'
    | '/private/student/practice'
    | '/private/student/profile'
    | '/private/student/research'
    | '/private/student/self-analysis'
    | '/private/student/statement'
    | '/business/actor/'
    | '/business/company/'
    | '/business/school/'
    | '/private/individual/'
    | '/private/student/'
    | '/business/actor/screening_/history'
    | '/business/company/screening_/history'
    | '/business/school/screening_/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarLabRoute: typeof AvatarLabRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MypageRoute: typeof MypageRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ScreeningRoute: typeof ScreeningRoute
  TermsRoute: typeof TermsRoute
  TokushoRoute: typeof TokushoRoute
  ActorInterviewTokenRoute: typeof ActorInterviewTokenRoute
  ApiActorInterviewTurnRoute: typeof ApiActorInterviewTurnRoute
  ApiAdminDashboardDataRoute: typeof ApiAdminDashboardDataRoute
  ApiAdminTriggerActorDiscoveryRoute: typeof ApiAdminTriggerActorDiscoveryRoute
  ApiAgencyDashboardDataRoute: typeof ApiAgencyDashboardDataRoute
  ApiBulkResearchActorsRoute: typeof ApiBulkResearchActorsRoute
  ApiCancelSubscriptionRoute: typeof ApiCancelSubscriptionRoute
  ApiCandidateDatabaseRoute: typeof ApiCandidateDatabaseRoute
  ApiCareerChatRoute: typeof ApiCareerChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatInterviewInfoRoute: typeof ApiChatInterviewInfoRoute
  ApiChatInterviewTurnRoute: typeof ApiChatInterviewTurnRoute
  ApiCreateActorInterviewRoute: typeof ApiCreateActorInterviewRoute
  ApiCreatePracticeSessionRoute: typeof ApiCreatePracticeSessionRoute
  ApiCreateSubscriptionRoute: typeof ApiCreateSubscriptionRoute
  ApiCustomerPortalRoute: typeof ApiCustomerPortalRoute
  ApiDailyQuestionRoute: typeof ApiDailyQuestionRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiExtractTemplateFieldsRoute: typeof ApiExtractTemplateFieldsRoute
  ApiGenerateDocumentRoute: typeof ApiGenerateDocumentRoute
  ApiGenerateSelfAnalysisRoute: typeof ApiGenerateSelfAnalysisRoute
  ApiInterviewTurnRoute: typeof ApiInterviewTurnRoute
  ApiPredictTicketSalesRoute: typeof ApiPredictTicketSalesRoute
  ApiRecordReferralRoute: typeof ApiRecordReferralRoute
  ApiRefineDocumentRoute: typeof ApiRefineDocumentRoute
  ApiRegisterDeviceRoute: typeof ApiRegisterDeviceRoute
  ApiReportUsageRoute: typeof ApiReportUsageRoute
  ApiResearchActorRoute: typeof ApiResearchActorRoute
  ApiResearchCompanyRoute: typeof ApiResearchCompanyRoute
  ApiResearchTargetRoute: typeof ApiResearchTargetRoute
  ApiSaveActorInterviewRoute: typeof ApiSaveActorInterviewRoute
  ApiSaveInterviewRoute: typeof ApiSaveInterviewRoute
  ApiSaveInterviewRecordingRoute: typeof ApiSaveInterviewRecordingRoute
  ApiScreenActorsBatchRoute: typeof ApiScreenActorsBatchRoute
  ApiSendInterviewEmailRoute: typeof ApiSendInterviewEmailRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiToggleCandidateBookmarkRoute: typeof ApiToggleCandidateBookmarkRoute
  ApiWhisperTranscribeRoute: typeof ApiWhisperTranscribeRoute
  ChatInterviewTokenRoute: typeof ChatInterviewTokenRoute
  InterviewTokenRoute: typeof InterviewTokenRoute
  PrivateAdminRoute: typeof PrivateAdminRoute
  PrivateAgencyRoute: typeof PrivateAgencyRoute
  PrivateWelcomeRoute: typeof PrivateWelcomeRoute
  ScreeningHistoryRoute: typeof ScreeningHistoryRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  BusinessActorDatabaseRoute: typeof BusinessActorDatabaseRoute
  BusinessActorHistoryRoute: typeof BusinessActorHistoryRoute
  BusinessActorScreeningRoute: typeof BusinessActorScreeningRoute
  BusinessCompanyCandidatesRoute: typeof BusinessCompanyCandidatesRoute
  BusinessCompanyHistoryRoute: typeof BusinessCompanyHistoryRoute
  BusinessCompanyJobsRoute: typeof BusinessCompanyJobsRoute
  BusinessCompanyScreeningRoute: typeof BusinessCompanyScreeningRoute
  BusinessCompanySettingsRoute: typeof BusinessCompanySettingsRoute
  BusinessSchoolHistoryRoute: typeof BusinessSchoolHistoryRoute
  BusinessSchoolScreeningRoute: typeof BusinessSchoolScreeningRoute
  BusinessSchoolSettingsRoute: typeof BusinessSchoolSettingsRoute
  BusinessSchoolStudentsRoute: typeof BusinessSchoolStudentsRoute
  PrivateIndividualDailyQuestionsRoute: typeof PrivateIndividualDailyQuestionsRoute
  PrivateIndividualDocumentsRoute: typeof PrivateIndividualDocumentsRoute
  PrivateIndividualHistoryRoute: typeof PrivateIndividualHistoryRoute
  PrivateIndividualOnboardingRoute: typeof PrivateIndividualOnboardingRoute
  PrivateIndividualPracticeRoute: typeof PrivateIndividualPracticeRoute
  PrivateIndividualPrepRoute: typeof PrivateIndividualPrepRoute
  PrivateIndividualProfileRoute: typeof PrivateIndividualProfileRoute
  PrivateIndividualResearchRoute: typeof PrivateIndividualResearchRoute
  PrivateIndividualSelfAnalysisRoute: typeof PrivateIndividualSelfAnalysisRoute
  PrivateStudentDailyQuestionsRoute: typeof PrivateStudentDailyQuestionsRoute
  PrivateStudentDocumentsRoute: typeof PrivateStudentDocumentsRoute
  PrivateStudentHistoryRoute: typeof PrivateStudentHistoryRoute
  PrivateStudentOnboardingRoute: typeof PrivateStudentOnboardingRoute
  PrivateStudentPracticeRoute: typeof PrivateStudentPracticeRoute
  PrivateStudentProfileRoute: typeof PrivateStudentProfileRoute
  PrivateStudentResearchRoute: typeof PrivateStudentResearchRoute
  PrivateStudentSelfAnalysisRoute: typeof PrivateStudentSelfAnalysisRoute
  PrivateStudentStatementRoute: typeof PrivateStudentStatementRoute
  BusinessActorIndexRoute: typeof BusinessActorIndexRoute
  BusinessCompanyIndexRoute: typeof BusinessCompanyIndexRoute
  BusinessSchoolIndexRoute: typeof BusinessSchoolIndexRoute
  PrivateIndividualIndexRoute: typeof PrivateIndividualIndexRoute
  PrivateStudentIndexRoute: typeof PrivateStudentIndexRoute
  BusinessActorScreeningHistoryRoute: typeof BusinessActorScreeningHistoryRoute
  BusinessCompanyScreeningHistoryRoute: typeof BusinessCompanyScreeningHistoryRoute
  BusinessSchoolScreeningHistoryRoute: typeof BusinessSchoolScreeningHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar-lab': {
      id: '/avatar-lab'
      path: '/avatar-lab'
      fullPath: '/avatar-lab'
      preLoaderRoute: typeof AvatarLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokusho': {
      id: '/tokusho'
      path: '/tokusho'
      fullPath: '/tokusho'
      preLoaderRoute: typeof TokushoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor-interview/$token': {
      id: '/actor-interview/$token'
      path: '/actor-interview/$token'
      fullPath: '/actor-interview/$token'
      preLoaderRoute: typeof ActorInterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actor-interview-turn': {
      id: '/api/actor-interview-turn'
      path: '/api/actor-interview-turn'
      fullPath: '/api/actor-interview-turn'
      preLoaderRoute: typeof ApiActorInterviewTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-dashboard-data': {
      id: '/api/admin-dashboard-data'
      path: '/api/admin-dashboard-data'
      fullPath: '/api/admin-dashboard-data'
      preLoaderRoute: typeof ApiAdminDashboardDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-trigger-actor-discovery': {
      id: '/api/admin-trigger-actor-discovery'
      path: '/api/admin-trigger-actor-discovery'
      fullPath: '/api/admin-trigger-actor-discovery'
      preLoaderRoute: typeof ApiAdminTriggerActorDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agency-dashboard-data': {
      id: '/api/agency-dashboard-data'
      path: '/api/agency-dashboard-data'
      fullPath: '/api/agency-dashboard-data'
      preLoaderRoute: typeof ApiAgencyDashboardDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bulk-research-actors': {
      id: '/api/bulk-research-actors'
      path: '/api/bulk-research-actors'
      fullPath: '/api/bulk-research-actors'
      preLoaderRoute: typeof ApiBulkResearchActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cancel-subscription': {
      id: '/api/cancel-subscription'
      path: '/api/cancel-subscription'
      fullPath: '/api/cancel-subscription'
      preLoaderRoute: typeof ApiCancelSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate-database': {
      id: '/api/candidate-database'
      path: '/api/candidate-database'
      fullPath: '/api/candidate-database'
      preLoaderRoute: typeof ApiCandidateDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career-chat': {
      id: '/api/career-chat'
      path: '/api/career-chat'
      fullPath: '/api/career-chat'
      preLoaderRoute: typeof ApiCareerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-interview-info': {
      id: '/api/chat-interview-info'
      path: '/api/chat-interview-info'
      fullPath: '/api/chat-interview-info'
      preLoaderRoute: typeof ApiChatInterviewInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-interview-turn': {
      id: '/api/chat-interview-turn'
      path: '/api/chat-interview-turn'
      fullPath: '/api/chat-interview-turn'
      preLoaderRoute: typeof ApiChatInterviewTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-actor-interview': {
      id: '/api/create-actor-interview'
      path: '/api/create-actor-interview'
      fullPath: '/api/create-actor-interview'
      preLoaderRoute: typeof ApiCreateActorInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-practice-session': {
      id: '/api/create-practice-session'
      path: '/api/create-practice-session'
      fullPath: '/api/create-practice-session'
      preLoaderRoute: typeof ApiCreatePracticeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-subscription': {
      id: '/api/create-subscription'
      path: '/api/create-subscription'
      fullPath: '/api/create-subscription'
      preLoaderRoute: typeof ApiCreateSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-portal': {
      id: '/api/customer-portal'
      path: '/api/customer-portal'
      fullPath: '/api/customer-portal'
      preLoaderRoute: typeof ApiCustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-question': {
      id: '/api/daily-question'
      path: '/api/daily-question'
      fullPath: '/api/daily-question'
      preLoaderRoute: typeof ApiDailyQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-template-fields': {
      id: '/api/extract-template-fields'
      path: '/api/extract-template-fields'
      fullPath: '/api/extract-template-fields'
      preLoaderRoute: typeof ApiExtractTemplateFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-document': {
      id: '/api/generate-document'
      path: '/api/generate-document'
      fullPath: '/api/generate-document'
      preLoaderRoute: typeof ApiGenerateDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-self-analysis': {
      id: '/api/generate-self-analysis'
      path: '/api/generate-self-analysis'
      fullPath: '/api/generate-self-analysis'
      preLoaderRoute: typeof ApiGenerateSelfAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-turn': {
      id: '/api/interview-turn'
      path: '/api/interview-turn'
      fullPath: '/api/interview-turn'
      preLoaderRoute: typeof ApiInterviewTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predict-ticket-sales': {
      id: '/api/predict-ticket-sales'
      path: '/api/predict-ticket-sales'
      fullPath: '/api/predict-ticket-sales'
      preLoaderRoute: typeof ApiPredictTicketSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/record-referral': {
      id: '/api/record-referral'
      path: '/api/record-referral'
      fullPath: '/api/record-referral'
      preLoaderRoute: typeof ApiRecordReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refine-document': {
      id: '/api/refine-document'
      path: '/api/refine-document'
      fullPath: '/api/refine-document'
      preLoaderRoute: typeof ApiRefineDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register-device': {
      id: '/api/register-device'
      path: '/api/register-device'
      fullPath: '/api/register-device'
      preLoaderRoute: typeof ApiRegisterDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-usage': {
      id: '/api/report-usage'
      path: '/api/report-usage'
      fullPath: '/api/report-usage'
      preLoaderRoute: typeof ApiReportUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research-actor': {
      id: '/api/research-actor'
      path: '/api/research-actor'
      fullPath: '/api/research-actor'
      preLoaderRoute: typeof ApiResearchActorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research-company': {
      id: '/api/research-company'
      path: '/api/research-company'
      fullPath: '/api/research-company'
      preLoaderRoute: typeof ApiResearchCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research-target': {
      id: '/api/research-target'
      path: '/api/research-target'
      fullPath: '/api/research-target'
      preLoaderRoute: typeof ApiResearchTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-actor-interview': {
      id: '/api/save-actor-interview'
      path: '/api/save-actor-interview'
      fullPath: '/api/save-actor-interview'
      preLoaderRoute: typeof ApiSaveActorInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-interview': {
      id: '/api/save-interview'
      path: '/api/save-interview'
      fullPath: '/api/save-interview'
      preLoaderRoute: typeof ApiSaveInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-interview-recording': {
      id: '/api/save-interview-recording'
      path: '/api/save-interview-recording'
      fullPath: '/api/save-interview-recording'
      preLoaderRoute: typeof ApiSaveInterviewRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screen-actors-batch': {
      id: '/api/screen-actors-batch'
      path: '/api/screen-actors-batch'
      fullPath: '/api/screen-actors-batch'
      preLoaderRoute: typeof ApiScreenActorsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-interview-email': {
      id: '/api/send-interview-email'
      path: '/api/send-interview-email'
      fullPath: '/api/send-interview-email'
      preLoaderRoute: typeof ApiSendInterviewEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/toggle-candidate-bookmark': {
      id: '/api/toggle-candidate-bookmark'
      path: '/api/toggle-candidate-bookmark'
      fullPath: '/api/toggle-candidate-bookmark'
      preLoaderRoute: typeof ApiToggleCandidateBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whisper-transcribe': {
      id: '/api/whisper-transcribe'
      path: '/api/whisper-transcribe'
      fullPath: '/api/whisper-transcribe'
      preLoaderRoute: typeof ApiWhisperTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-interview/$token': {
      id: '/chat-interview/$token'
      path: '/chat-interview/$token'
      fullPath: '/chat-interview/$token'
      preLoaderRoute: typeof ChatInterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$token': {
      id: '/interview/$token'
      path: '/interview/$token'
      fullPath: '/interview/$token'
      preLoaderRoute: typeof InterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/': {
      id: '/private/'
      path: '/private'
      fullPath: '/private/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/admin': {
      id: '/private/admin'
      path: '/private/admin'
      fullPath: '/private/admin'
      preLoaderRoute: typeof PrivateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/agency': {
      id: '/private/agency'
      path: '/private/agency'
      fullPath: '/private/agency'
      preLoaderRoute: typeof PrivateAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/welcome': {
      id: '/private/welcome'
      path: '/private/welcome'
      fullPath: '/private/welcome'
      preLoaderRoute: typeof PrivateWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening_/history': {
      id: '/screening_/history'
      path: '/screening/history'
      fullPath: '/screening/history'
      preLoaderRoute: typeof ScreeningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/actor/': {
      id: '/business/actor/'
      path: '/business/actor'
      fullPath: '/business/actor/'
      preLoaderRoute: typeof BusinessActorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/actor/database': {
      id: '/business/actor/database'
      path: '/business/actor/database'
      fullPath: '/business/actor/database'
      preLoaderRoute: typeof BusinessActorDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/actor/history': {
      id: '/business/actor/history'
      path: '/business/actor/history'
      fullPath: '/business/actor/history'
      preLoaderRoute: typeof BusinessActorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/actor/screening': {
      id: '/business/actor/screening'
      path: '/business/actor/screening'
      fullPath: '/business/actor/screening'
      preLoaderRoute: typeof BusinessActorScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/': {
      id: '/business/company/'
      path: '/business/company'
      fullPath: '/business/company/'
      preLoaderRoute: typeof BusinessCompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/candidates': {
      id: '/business/company/candidates'
      path: '/business/company/candidates'
      fullPath: '/business/company/candidates'
      preLoaderRoute: typeof BusinessCompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/history': {
      id: '/business/company/history'
      path: '/business/company/history'
      fullPath: '/business/company/history'
      preLoaderRoute: typeof BusinessCompanyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/jobs': {
      id: '/business/company/jobs'
      path: '/business/company/jobs'
      fullPath: '/business/company/jobs'
      preLoaderRoute: typeof BusinessCompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/screening': {
      id: '/business/company/screening'
      path: '/business/company/screening'
      fullPath: '/business/company/screening'
      preLoaderRoute: typeof BusinessCompanyScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/settings': {
      id: '/business/company/settings'
      path: '/business/company/settings'
      fullPath: '/business/company/settings'
      preLoaderRoute: typeof BusinessCompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/': {
      id: '/business/school/'
      path: '/business/school'
      fullPath: '/business/school/'
      preLoaderRoute: typeof BusinessSchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/history': {
      id: '/business/school/history'
      path: '/business/school/history'
      fullPath: '/business/school/history'
      preLoaderRoute: typeof BusinessSchoolHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/screening': {
      id: '/business/school/screening'
      path: '/business/school/screening'
      fullPath: '/business/school/screening'
      preLoaderRoute: typeof BusinessSchoolScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/settings': {
      id: '/business/school/settings'
      path: '/business/school/settings'
      fullPath: '/business/school/settings'
      preLoaderRoute: typeof BusinessSchoolSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/students': {
      id: '/business/school/students'
      path: '/business/school/students'
      fullPath: '/business/school/students'
      preLoaderRoute: typeof BusinessSchoolStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/': {
      id: '/private/individual/'
      path: '/private/individual'
      fullPath: '/private/individual/'
      preLoaderRoute: typeof PrivateIndividualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/daily-questions': {
      id: '/private/individual/daily-questions'
      path: '/private/individual/daily-questions'
      fullPath: '/private/individual/daily-questions'
      preLoaderRoute: typeof PrivateIndividualDailyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/documents': {
      id: '/private/individual/documents'
      path: '/private/individual/documents'
      fullPath: '/private/individual/documents'
      preLoaderRoute: typeof PrivateIndividualDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/history': {
      id: '/private/individual/history'
      path: '/private/individual/history'
      fullPath: '/private/individual/history'
      preLoaderRoute: typeof PrivateIndividualHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/onboarding': {
      id: '/private/individual/onboarding'
      path: '/private/individual/onboarding'
      fullPath: '/private/individual/onboarding'
      preLoaderRoute: typeof PrivateIndividualOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/practice': {
      id: '/private/individual/practice'
      path: '/private/individual/practice'
      fullPath: '/private/individual/practice'
      preLoaderRoute: typeof PrivateIndividualPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/prep': {
      id: '/private/individual/prep'
      path: '/private/individual/prep'
      fullPath: '/private/individual/prep'
      preLoaderRoute: typeof PrivateIndividualPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/profile': {
      id: '/private/individual/profile'
      path: '/private/individual/profile'
      fullPath: '/private/individual/profile'
      preLoaderRoute: typeof PrivateIndividualProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/research': {
      id: '/private/individual/research'
      path: '/private/individual/research'
      fullPath: '/private/individual/research'
      preLoaderRoute: typeof PrivateIndividualResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/individual/self-analysis': {
      id: '/private/individual/self-analysis'
      path: '/private/individual/self-analysis'
      fullPath: '/private/individual/self-analysis'
      preLoaderRoute: typeof PrivateIndividualSelfAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/': {
      id: '/private/student/'
      path: '/private/student'
      fullPath: '/private/student/'
      preLoaderRoute: typeof PrivateStudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/daily-questions': {
      id: '/private/student/daily-questions'
      path: '/private/student/daily-questions'
      fullPath: '/private/student/daily-questions'
      preLoaderRoute: typeof PrivateStudentDailyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/documents': {
      id: '/private/student/documents'
      path: '/private/student/documents'
      fullPath: '/private/student/documents'
      preLoaderRoute: typeof PrivateStudentDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/history': {
      id: '/private/student/history'
      path: '/private/student/history'
      fullPath: '/private/student/history'
      preLoaderRoute: typeof PrivateStudentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/onboarding': {
      id: '/private/student/onboarding'
      path: '/private/student/onboarding'
      fullPath: '/private/student/onboarding'
      preLoaderRoute: typeof PrivateStudentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/practice': {
      id: '/private/student/practice'
      path: '/private/student/practice'
      fullPath: '/private/student/practice'
      preLoaderRoute: typeof PrivateStudentPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/profile': {
      id: '/private/student/profile'
      path: '/private/student/profile'
      fullPath: '/private/student/profile'
      preLoaderRoute: typeof PrivateStudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/research': {
      id: '/private/student/research'
      path: '/private/student/research'
      fullPath: '/private/student/research'
      preLoaderRoute: typeof PrivateStudentResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/self-analysis': {
      id: '/private/student/self-analysis'
      path: '/private/student/self-analysis'
      fullPath: '/private/student/self-analysis'
      preLoaderRoute: typeof PrivateStudentSelfAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/student/statement': {
      id: '/private/student/statement'
      path: '/private/student/statement'
      fullPath: '/private/student/statement'
      preLoaderRoute: typeof PrivateStudentStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/actor/screening_/history': {
      id: '/business/actor/screening_/history'
      path: '/business/actor/screening/history'
      fullPath: '/business/actor/screening/history'
      preLoaderRoute: typeof BusinessActorScreeningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/company/screening_/history': {
      id: '/business/company/screening_/history'
      path: '/business/company/screening/history'
      fullPath: '/business/company/screening/history'
      preLoaderRoute: typeof BusinessCompanyScreeningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/school/screening_/history': {
      id: '/business/school/screening_/history'
      path: '/business/school/screening/history'
      fullPath: '/business/school/screening/history'
      preLoaderRoute: typeof BusinessSchoolScreeningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarLabRoute: AvatarLabRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ScreeningRoute: ScreeningRoute,
  TermsRoute: TermsRoute,
  TokushoRoute: TokushoRoute,
  ActorInterviewTokenRoute: ActorInterviewTokenRoute,
  ApiActorInterviewTurnRoute: ApiActorInterviewTurnRoute,
  ApiAdminDashboardDataRoute: ApiAdminDashboardDataRoute,
  ApiAdminTriggerActorDiscoveryRoute: ApiAdminTriggerActorDiscoveryRoute,
  ApiAgencyDashboardDataRoute: ApiAgencyDashboardDataRoute,
  ApiBulkResearchActorsRoute: ApiBulkResearchActorsRoute,
  ApiCancelSubscriptionRoute: ApiCancelSubscriptionRoute,
  ApiCandidateDatabaseRoute: ApiCandidateDatabaseRoute,
  ApiCareerChatRoute: ApiCareerChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatInterviewInfoRoute: ApiChatInterviewInfoRoute,
  ApiChatInterviewTurnRoute: ApiChatInterviewTurnRoute,
  ApiCreateActorInterviewRoute: ApiCreateActorInterviewRoute,
  ApiCreatePracticeSessionRoute: ApiCreatePracticeSessionRoute,
  ApiCreateSubscriptionRoute: ApiCreateSubscriptionRoute,
  ApiCustomerPortalRoute: ApiCustomerPortalRoute,
  ApiDailyQuestionRoute: ApiDailyQuestionRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiExtractTemplateFieldsRoute: ApiExtractTemplateFieldsRoute,
  ApiGenerateDocumentRoute: ApiGenerateDocumentRoute,
  ApiGenerateSelfAnalysisRoute: ApiGenerateSelfAnalysisRoute,
  ApiInterviewTurnRoute: ApiInterviewTurnRoute,
  ApiPredictTicketSalesRoute: ApiPredictTicketSalesRoute,
  ApiRecordReferralRoute: ApiRecordReferralRoute,
  ApiRefineDocumentRoute: ApiRefineDocumentRoute,
  ApiRegisterDeviceRoute: ApiRegisterDeviceRoute,
  ApiReportUsageRoute: ApiReportUsageRoute,
  ApiResearchActorRoute: ApiResearchActorRoute,
  ApiResearchCompanyRoute: ApiResearchCompanyRoute,
  ApiResearchTargetRoute: ApiResearchTargetRoute,
  ApiSaveActorInterviewRoute: ApiSaveActorInterviewRoute,
  ApiSaveInterviewRoute: ApiSaveInterviewRoute,
  ApiSaveInterviewRecordingRoute: ApiSaveInterviewRecordingRoute,
  ApiScreenActorsBatchRoute: ApiScreenActorsBatchRoute,
  ApiSendInterviewEmailRoute: ApiSendInterviewEmailRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiToggleCandidateBookmarkRoute: ApiToggleCandidateBookmarkRoute,
  ApiWhisperTranscribeRoute: ApiWhisperTranscribeRoute,
  ChatInterviewTokenRoute: ChatInterviewTokenRoute,
  InterviewTokenRoute: InterviewTokenRoute,
  PrivateAdminRoute: PrivateAdminRoute,
  PrivateAgencyRoute: PrivateAgencyRoute,
  PrivateWelcomeRoute: PrivateWelcomeRoute,
  ScreeningHistoryRoute: ScreeningHistoryRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  BusinessActorDatabaseRoute: BusinessActorDatabaseRoute,
  BusinessActorHistoryRoute: BusinessActorHistoryRoute,
  BusinessActorScreeningRoute: BusinessActorScreeningRoute,
  BusinessCompanyCandidatesRoute: BusinessCompanyCandidatesRoute,
  BusinessCompanyHistoryRoute: BusinessCompanyHistoryRoute,
  BusinessCompanyJobsRoute: BusinessCompanyJobsRoute,
  BusinessCompanyScreeningRoute: BusinessCompanyScreeningRoute,
  BusinessCompanySettingsRoute: BusinessCompanySettingsRoute,
  BusinessSchoolHistoryRoute: BusinessSchoolHistoryRoute,
  BusinessSchoolScreeningRoute: BusinessSchoolScreeningRoute,
  BusinessSchoolSettingsRoute: BusinessSchoolSettingsRoute,
  BusinessSchoolStudentsRoute: BusinessSchoolStudentsRoute,
  PrivateIndividualDailyQuestionsRoute: PrivateIndividualDailyQuestionsRoute,
  PrivateIndividualDocumentsRoute: PrivateIndividualDocumentsRoute,
  PrivateIndividualHistoryRoute: PrivateIndividualHistoryRoute,
  PrivateIndividualOnboardingRoute: PrivateIndividualOnboardingRoute,
  PrivateIndividualPracticeRoute: PrivateIndividualPracticeRoute,
  PrivateIndividualPrepRoute: PrivateIndividualPrepRoute,
  PrivateIndividualProfileRoute: PrivateIndividualProfileRoute,
  PrivateIndividualResearchRoute: PrivateIndividualResearchRoute,
  PrivateIndividualSelfAnalysisRoute: PrivateIndividualSelfAnalysisRoute,
  PrivateStudentDailyQuestionsRoute: PrivateStudentDailyQuestionsRoute,
  PrivateStudentDocumentsRoute: PrivateStudentDocumentsRoute,
  PrivateStudentHistoryRoute: PrivateStudentHistoryRoute,
  PrivateStudentOnboardingRoute: PrivateStudentOnboardingRoute,
  PrivateStudentPracticeRoute: PrivateStudentPracticeRoute,
  PrivateStudentProfileRoute: PrivateStudentProfileRoute,
  PrivateStudentResearchRoute: PrivateStudentResearchRoute,
  PrivateStudentSelfAnalysisRoute: PrivateStudentSelfAnalysisRoute,
  PrivateStudentStatementRoute: PrivateStudentStatementRoute,
  BusinessActorIndexRoute: BusinessActorIndexRoute,
  BusinessCompanyIndexRoute: BusinessCompanyIndexRoute,
  BusinessSchoolIndexRoute: BusinessSchoolIndexRoute,
  PrivateIndividualIndexRoute: PrivateIndividualIndexRoute,
  PrivateStudentIndexRoute: PrivateStudentIndexRoute,
  BusinessActorScreeningHistoryRoute: BusinessActorScreeningHistoryRoute,
  BusinessCompanyScreeningHistoryRoute: BusinessCompanyScreeningHistoryRoute,
  BusinessSchoolScreeningHistoryRoute: BusinessSchoolScreeningHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
